### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by caminsha** [lobbywatch/website#62]
Thanks for providing this great project.

As you did with some other repositories it would be nice if you'd add a License for this repository.

**Comment by tpreusse** [comment]
It is BSD-3-Clause:
https://github.com/lobbywatch/website/blob/f5ee286624c658e5247b3212be69544b42ea253b/package.json#L19

But please don't copy the branding :D I shall add something to the readme and a proper license file.

**Comment by caminsha** [comment]
Thanks for the fast reply!
> It is BSD-3-Clause:
> 
> https://github.com/lobbywatch/website/blob/f5ee286624c658e5247b3212be69544b42ea253b/package.json#L19
Ah nice, didn't see it. 
> 
> But please don't copy the branding :D I shall add something to the readme and a proper license file.
No, I won't. :) Something in the Readme would make it easier to see the license, yes.
