### ISSUE TITLE
Allow using ctrl- and shift-click to open subjects in new tab or window

### ISSUE THREAD

**Issue by knutwannheden** [lobbywatch/website#63]
Currently a ctrl-click or shift-click on a subject in the UI is no different from a normal click. It would be nice if ctrl-click and shift-click would be detected and allow the user to open the linked subject in a separate tab or window.

So if I on https://lobbywatch.ch/de/daten/organisation/5293/Campus%20f%C3%BCr%20Demokratie ctrl-click on "Stiftung Dialog" I would like the linked organization to open in a new tab.

**Comment by knutwannheden** [comment]
As another alternative it would also be possible to add a small link icon to the nodes on the diagram. Clicking on this icon would have the effect of opening the referenced subject. This would have the nice side-effect that more pages can be linked to (e.g. from the parliamentarian page the user could navigate to the guest or lobby group pages). The downside is added clutter.

**Comment by tpreusse** [comment]
Should now work. Let me know if there is somewhere you'd expect it to work but doesn't yet.

**Comment by knutwannheden** [comment]
One aspect of the UX has now changed: When clicking on a _Zutrittsberechtigter_ node on a _Parlamentarier_ page, that will not only expand the node but also open the corresponding page. As a result the user doesn't really have time to look at the expanded child nodes anymore. While I personally think it would be nice to also be able to navigate to the referenced page, it must be possible to only expand the child nodes.

The easiest solution would be to revert this aspect to the previous behavior. As an alternative we could also discuss the possibility of adding a link icon (as hinted at in my previous comment: https://github.com/lobbywatch/website/issues/63#issuecomment-1089274250).

**Comment by tpreusse** [comment]
@knutwannheden ooops, that was a sloppy coding oversight. Fixed with https://github.com/lobbywatch/website/commit/5d58c64e3fb71946982dcc04ea0870c67b547d7e – thanks for reporting
